import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import {AnimatePresence} from "framer-motion";

const inter = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <div id={`root`}>
      {children}
    </div>
    <div id={`portal`}></div>
    </body>
    </html>
  );
}
